/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallIndexRouteImport } from './routes/wall/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthQuarryIndexRouteImport } from './routes/_auth/quarry/index'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsUriRouteImport } from './routes/api/assets/$uri'
import { Route as AuthQuarryProjectsRouteRouteImport } from './routes/_auth/quarry/projects/route'
import { Route as AuthQuarryEditorRouteRouteImport } from './routes/_auth/quarry/editor/route'
import { Route as AuthQuarryProjectsNewRouteImport } from './routes/_auth/quarry/projects/new'
import { Route as AuthQuarryProjectsProjectIdRouteRouteImport } from './routes/_auth/quarry/projects/$projectId/route'
import { Route as AuthQuarryProjectsProjectIdIndexRouteImport } from './routes/_auth/quarry/projects/$projectId/index'
import { Route as AuthQuarryEditorProjectIdIndexRouteImport } from './routes/_auth/quarry/editor/$projectId/index'
import { Route as AuthQuarryProjectsProjectIdPermissionsRouteImport } from './routes/_auth/quarry/projects/$projectId/permissions'
import { Route as AuthQuarryProjectsProjectIdHistoryRouteImport } from './routes/_auth/quarry/projects/$projectId/history'
import { Route as AuthQuarryProjectsProjectIdCommitsRouteImport } from './routes/_auth/quarry/projects/$projectId/commits'
import { Route as AuthQuarryProjectsProjectIdAssetsRouteImport } from './routes/_auth/quarry/projects/$projectId/assets'
import { Route as AuthQuarryEditorProjectIdSlideIdRouteImport } from './routes/_auth/quarry/editor/$projectId/$slideId'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallIndexRoute = WallIndexRouteImport.update({
  id: '/wall/',
  path: '/wall/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthQuarryIndexRoute = AuthQuarryIndexRouteImport.update({
  id: '/quarry/',
  path: '/quarry/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsUriRoute = ApiAssetsUriRouteImport.update({
  id: '/api/assets/$uri',
  path: '/api/assets/$uri',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthQuarryProjectsRouteRoute = AuthQuarryProjectsRouteRouteImport.update({
  id: '/quarry/projects',
  path: '/quarry/projects',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthQuarryEditorRouteRoute = AuthQuarryEditorRouteRouteImport.update({
  id: '/quarry/editor',
  path: '/quarry/editor',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthQuarryProjectsNewRoute = AuthQuarryProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthQuarryProjectsRouteRoute,
} as any)
const AuthQuarryProjectsProjectIdRouteRoute =
  AuthQuarryProjectsProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthQuarryProjectsRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdIndexRoute =
  AuthQuarryProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryEditorProjectIdIndexRoute =
  AuthQuarryEditorProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => AuthQuarryEditorRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdPermissionsRoute =
  AuthQuarryProjectsProjectIdPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdHistoryRoute =
  AuthQuarryProjectsProjectIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdCommitsRoute =
  AuthQuarryProjectsProjectIdCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdAssetsRoute =
  AuthQuarryProjectsProjectIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryEditorProjectIdSlideIdRoute =
  AuthQuarryEditorProjectIdSlideIdRouteImport.update({
    id: '/$projectId/$slideId',
    path: '/$projectId/$slideId',
    getParentRoute: () => AuthQuarryEditorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/login': typeof GuestLoginRoute
  '/gallery/': typeof GalleryIndexRoute
  '/wall/': typeof WallIndexRoute
  '/quarry/editor': typeof AuthQuarryEditorRouteRouteWithChildren
  '/quarry/projects': typeof AuthQuarryProjectsRouteRouteWithChildren
  '/api/assets/$uri': typeof ApiAssetsUriRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/quarry/': typeof AuthQuarryIndexRoute
  '/quarry/projects/$projectId': typeof AuthQuarryProjectsProjectIdRouteRouteWithChildren
  '/quarry/projects/new': typeof AuthQuarryProjectsNewRoute
  '/quarry/editor/$projectId/$slideId': typeof AuthQuarryEditorProjectIdSlideIdRoute
  '/quarry/projects/$projectId/assets': typeof AuthQuarryProjectsProjectIdAssetsRoute
  '/quarry/projects/$projectId/commits': typeof AuthQuarryProjectsProjectIdCommitsRoute
  '/quarry/projects/$projectId/history': typeof AuthQuarryProjectsProjectIdHistoryRoute
  '/quarry/projects/$projectId/permissions': typeof AuthQuarryProjectsProjectIdPermissionsRoute
  '/quarry/editor/$projectId/': typeof AuthQuarryEditorProjectIdIndexRoute
  '/quarry/projects/$projectId/': typeof AuthQuarryProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/login': typeof GuestLoginRoute
  '/gallery': typeof GalleryIndexRoute
  '/wall': typeof WallIndexRoute
  '/quarry/editor': typeof AuthQuarryEditorRouteRouteWithChildren
  '/quarry/projects': typeof AuthQuarryProjectsRouteRouteWithChildren
  '/api/assets/$uri': typeof ApiAssetsUriRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/quarry': typeof AuthQuarryIndexRoute
  '/quarry/projects/new': typeof AuthQuarryProjectsNewRoute
  '/quarry/editor/$projectId/$slideId': typeof AuthQuarryEditorProjectIdSlideIdRoute
  '/quarry/projects/$projectId/assets': typeof AuthQuarryProjectsProjectIdAssetsRoute
  '/quarry/projects/$projectId/commits': typeof AuthQuarryProjectsProjectIdCommitsRoute
  '/quarry/projects/$projectId/history': typeof AuthQuarryProjectsProjectIdHistoryRoute
  '/quarry/projects/$projectId/permissions': typeof AuthQuarryProjectsProjectIdPermissionsRoute
  '/quarry/editor/$projectId': typeof AuthQuarryEditorProjectIdIndexRoute
  '/quarry/projects/$projectId': typeof AuthQuarryProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/og': typeof OgRoute
  '/_guest/login': typeof GuestLoginRoute
  '/gallery/': typeof GalleryIndexRoute
  '/wall/': typeof WallIndexRoute
  '/_auth/quarry/editor': typeof AuthQuarryEditorRouteRouteWithChildren
  '/_auth/quarry/projects': typeof AuthQuarryProjectsRouteRouteWithChildren
  '/api/assets/$uri': typeof ApiAssetsUriRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/_auth/quarry/': typeof AuthQuarryIndexRoute
  '/_auth/quarry/projects/$projectId': typeof AuthQuarryProjectsProjectIdRouteRouteWithChildren
  '/_auth/quarry/projects/new': typeof AuthQuarryProjectsNewRoute
  '/_auth/quarry/editor/$projectId/$slideId': typeof AuthQuarryEditorProjectIdSlideIdRoute
  '/_auth/quarry/projects/$projectId/assets': typeof AuthQuarryProjectsProjectIdAssetsRoute
  '/_auth/quarry/projects/$projectId/commits': typeof AuthQuarryProjectsProjectIdCommitsRoute
  '/_auth/quarry/projects/$projectId/history': typeof AuthQuarryProjectsProjectIdHistoryRoute
  '/_auth/quarry/projects/$projectId/permissions': typeof AuthQuarryProjectsProjectIdPermissionsRoute
  '/_auth/quarry/editor/$projectId/': typeof AuthQuarryEditorProjectIdIndexRoute
  '/_auth/quarry/projects/$projectId/': typeof AuthQuarryProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/og'
    | '/login'
    | '/gallery/'
    | '/wall/'
    | '/quarry/editor'
    | '/quarry/projects'
    | '/api/assets/$uri'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/quarry/'
    | '/quarry/projects/$projectId'
    | '/quarry/projects/new'
    | '/quarry/editor/$projectId/$slideId'
    | '/quarry/projects/$projectId/assets'
    | '/quarry/projects/$projectId/commits'
    | '/quarry/projects/$projectId/history'
    | '/quarry/projects/$projectId/permissions'
    | '/quarry/editor/$projectId/'
    | '/quarry/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og'
    | '/login'
    | '/gallery'
    | '/wall'
    | '/quarry/editor'
    | '/quarry/projects'
    | '/api/assets/$uri'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/quarry'
    | '/quarry/projects/new'
    | '/quarry/editor/$projectId/$slideId'
    | '/quarry/projects/$projectId/assets'
    | '/quarry/projects/$projectId/commits'
    | '/quarry/projects/$projectId/history'
    | '/quarry/projects/$projectId/permissions'
    | '/quarry/editor/$projectId'
    | '/quarry/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/og'
    | '/_guest/login'
    | '/gallery/'
    | '/wall/'
    | '/_auth/quarry/editor'
    | '/_auth/quarry/projects'
    | '/api/assets/$uri'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/_auth/quarry/'
    | '/_auth/quarry/projects/$projectId'
    | '/_auth/quarry/projects/new'
    | '/_auth/quarry/editor/$projectId/$slideId'
    | '/_auth/quarry/projects/$projectId/assets'
    | '/_auth/quarry/projects/$projectId/commits'
    | '/_auth/quarry/projects/$projectId/history'
    | '/_auth/quarry/projects/$projectId/permissions'
    | '/_auth/quarry/editor/$projectId/'
    | '/_auth/quarry/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  OgRoute: typeof OgRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  WallIndexRoute: typeof WallIndexRoute
  ApiAssetsUriRoute: typeof ApiAssetsUriRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall/': {
      id: '/wall/'
      path: '/wall'
      fullPath: '/wall/'
      preLoaderRoute: typeof WallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/quarry/': {
      id: '/_auth/quarry/'
      path: '/quarry'
      fullPath: '/quarry/'
      preLoaderRoute: typeof AuthQuarryIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$uri': {
      id: '/api/assets/$uri'
      path: '/api/assets/$uri'
      fullPath: '/api/assets/$uri'
      preLoaderRoute: typeof ApiAssetsUriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/quarry/projects': {
      id: '/_auth/quarry/projects'
      path: '/quarry/projects'
      fullPath: '/quarry/projects'
      preLoaderRoute: typeof AuthQuarryProjectsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/quarry/editor': {
      id: '/_auth/quarry/editor'
      path: '/quarry/editor'
      fullPath: '/quarry/editor'
      preLoaderRoute: typeof AuthQuarryEditorRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/quarry/projects/new': {
      id: '/_auth/quarry/projects/new'
      path: '/new'
      fullPath: '/quarry/projects/new'
      preLoaderRoute: typeof AuthQuarryProjectsNewRouteImport
      parentRoute: typeof AuthQuarryProjectsRouteRoute
    }
    '/_auth/quarry/projects/$projectId': {
      id: '/_auth/quarry/projects/$projectId'
      path: '/$projectId'
      fullPath: '/quarry/projects/$projectId'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthQuarryProjectsRouteRoute
    }
    '/_auth/quarry/projects/$projectId/': {
      id: '/_auth/quarry/projects/$projectId/'
      path: '/'
      fullPath: '/quarry/projects/$projectId/'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/editor/$projectId/': {
      id: '/_auth/quarry/editor/$projectId/'
      path: '/$projectId'
      fullPath: '/quarry/editor/$projectId/'
      preLoaderRoute: typeof AuthQuarryEditorProjectIdIndexRouteImport
      parentRoute: typeof AuthQuarryEditorRouteRoute
    }
    '/_auth/quarry/projects/$projectId/permissions': {
      id: '/_auth/quarry/projects/$projectId/permissions'
      path: '/permissions'
      fullPath: '/quarry/projects/$projectId/permissions'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdPermissionsRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/projects/$projectId/history': {
      id: '/_auth/quarry/projects/$projectId/history'
      path: '/history'
      fullPath: '/quarry/projects/$projectId/history'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdHistoryRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/projects/$projectId/commits': {
      id: '/_auth/quarry/projects/$projectId/commits'
      path: '/commits'
      fullPath: '/quarry/projects/$projectId/commits'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdCommitsRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/projects/$projectId/assets': {
      id: '/_auth/quarry/projects/$projectId/assets'
      path: '/assets'
      fullPath: '/quarry/projects/$projectId/assets'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdAssetsRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/editor/$projectId/$slideId': {
      id: '/_auth/quarry/editor/$projectId/$slideId'
      path: '/$projectId/$slideId'
      fullPath: '/quarry/editor/$projectId/$slideId'
      preLoaderRoute: typeof AuthQuarryEditorProjectIdSlideIdRouteImport
      parentRoute: typeof AuthQuarryEditorRouteRoute
    }
  }
}

interface AuthQuarryEditorRouteRouteChildren {
  AuthQuarryEditorProjectIdSlideIdRoute: typeof AuthQuarryEditorProjectIdSlideIdRoute
  AuthQuarryEditorProjectIdIndexRoute: typeof AuthQuarryEditorProjectIdIndexRoute
}

const AuthQuarryEditorRouteRouteChildren: AuthQuarryEditorRouteRouteChildren = {
  AuthQuarryEditorProjectIdSlideIdRoute: AuthQuarryEditorProjectIdSlideIdRoute,
  AuthQuarryEditorProjectIdIndexRoute: AuthQuarryEditorProjectIdIndexRoute,
}

const AuthQuarryEditorRouteRouteWithChildren =
  AuthQuarryEditorRouteRoute._addFileChildren(
    AuthQuarryEditorRouteRouteChildren,
  )

interface AuthQuarryProjectsProjectIdRouteRouteChildren {
  AuthQuarryProjectsProjectIdAssetsRoute: typeof AuthQuarryProjectsProjectIdAssetsRoute
  AuthQuarryProjectsProjectIdCommitsRoute: typeof AuthQuarryProjectsProjectIdCommitsRoute
  AuthQuarryProjectsProjectIdHistoryRoute: typeof AuthQuarryProjectsProjectIdHistoryRoute
  AuthQuarryProjectsProjectIdPermissionsRoute: typeof AuthQuarryProjectsProjectIdPermissionsRoute
  AuthQuarryProjectsProjectIdIndexRoute: typeof AuthQuarryProjectsProjectIdIndexRoute
}

const AuthQuarryProjectsProjectIdRouteRouteChildren: AuthQuarryProjectsProjectIdRouteRouteChildren =
  {
    AuthQuarryProjectsProjectIdAssetsRoute:
      AuthQuarryProjectsProjectIdAssetsRoute,
    AuthQuarryProjectsProjectIdCommitsRoute:
      AuthQuarryProjectsProjectIdCommitsRoute,
    AuthQuarryProjectsProjectIdHistoryRoute:
      AuthQuarryProjectsProjectIdHistoryRoute,
    AuthQuarryProjectsProjectIdPermissionsRoute:
      AuthQuarryProjectsProjectIdPermissionsRoute,
    AuthQuarryProjectsProjectIdIndexRoute:
      AuthQuarryProjectsProjectIdIndexRoute,
  }

const AuthQuarryProjectsProjectIdRouteRouteWithChildren =
  AuthQuarryProjectsProjectIdRouteRoute._addFileChildren(
    AuthQuarryProjectsProjectIdRouteRouteChildren,
  )

interface AuthQuarryProjectsRouteRouteChildren {
  AuthQuarryProjectsProjectIdRouteRoute: typeof AuthQuarryProjectsProjectIdRouteRouteWithChildren
  AuthQuarryProjectsNewRoute: typeof AuthQuarryProjectsNewRoute
}

const AuthQuarryProjectsRouteRouteChildren: AuthQuarryProjectsRouteRouteChildren =
  {
    AuthQuarryProjectsProjectIdRouteRoute:
      AuthQuarryProjectsProjectIdRouteRouteWithChildren,
    AuthQuarryProjectsNewRoute: AuthQuarryProjectsNewRoute,
  }

const AuthQuarryProjectsRouteRouteWithChildren =
  AuthQuarryProjectsRouteRoute._addFileChildren(
    AuthQuarryProjectsRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthQuarryEditorRouteRoute: typeof AuthQuarryEditorRouteRouteWithChildren
  AuthQuarryProjectsRouteRoute: typeof AuthQuarryProjectsRouteRouteWithChildren
  AuthQuarryIndexRoute: typeof AuthQuarryIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthQuarryEditorRouteRoute: AuthQuarryEditorRouteRouteWithChildren,
  AuthQuarryProjectsRouteRoute: AuthQuarryProjectsRouteRouteWithChildren,
  AuthQuarryIndexRoute: AuthQuarryIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  OgRoute: OgRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  WallIndexRoute: WallIndexRoute,
  ApiAssetsUriRoute: ApiAssetsUriRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
