/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebPlaceholderRouteImport } from './routes/web-placeholder'
import { Route as WebNonetRouteImport } from './routes/web-nonet'
import { Route as WebCorsissueRouteImport } from './routes/web-corsissue'
import { Route as OgRouteImport } from './routes/og'
import { Route as BusRouteImport } from './routes/bus'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallIndexRouteImport } from './routes/wall/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as ControllerIndexRouteImport } from './routes/controller/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as YjsSplatRouteImport } from './routes/yjs/$'
import { Route as UploadProjectIdRouteImport } from './routes/upload/$projectId'
import { Route as PlaygroundNoopRouteImport } from './routes/playground/noop'
import { Route as LegalNoticesRouteImport } from './routes/legal/notices'
import { Route as ApiWebScreenshotRouteImport } from './routes/api/web-screenshot'
import { Route as ApiReportCspRouteImport } from './routes/api/report-csp'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminDevicesRouteImport } from './routes/admin/devices'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminAssetsRouteImport } from './routes/admin/assets'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestBootstrapRouteImport } from './routes/_guest/bootstrap'
import { Route as AdminWallsIndexRouteImport } from './routes/admin/walls/index'
import { Route as AuthQuarryIndexRouteImport } from './routes/_auth/quarry/index'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsUriRouteImport } from './routes/api/assets/$uri'
import { Route as AdminWallsWallIdRouteRouteImport } from './routes/admin/walls/$wallId/route'
import { Route as AuthQuarryProjectsRouteRouteImport } from './routes/_auth/quarry/projects/route'
import { Route as AuthQuarryEditorRouteRouteImport } from './routes/_auth/quarry/editor/route'
import { Route as AdminWallsWallIdIndexRouteImport } from './routes/admin/walls/$wallId/index'
import { Route as ApiPortalV1RebootRouteImport } from './routes/api/portal/v1/reboot'
import { Route as AdminWallsWallIdDevicesRouteImport } from './routes/admin/walls/$wallId/devices'
import { Route as AuthQuarryProjectsNewRouteImport } from './routes/_auth/quarry/projects/new'
import { Route as AuthQuarryProjectsProjectIdRouteRouteImport } from './routes/_auth/quarry/projects/$projectId/route'
import { Route as AuthQuarryProjectsProjectIdIndexRouteImport } from './routes/_auth/quarry/projects/$projectId/index'
import { Route as AuthQuarryEditorProjectIdIndexRouteImport } from './routes/_auth/quarry/editor/$projectId/index'
import { Route as AuthQuarryViewProjectIdCommitIdRouteImport } from './routes/_auth/quarry/view/$projectId/$commitId'
import { Route as AuthQuarryProjectsProjectIdPermissionsRouteImport } from './routes/_auth/quarry/projects/$projectId/permissions'
import { Route as AuthQuarryProjectsProjectIdHistoryRouteImport } from './routes/_auth/quarry/projects/$projectId/history'
import { Route as AuthQuarryProjectsProjectIdCommitsRouteImport } from './routes/_auth/quarry/projects/$projectId/commits'
import { Route as AuthQuarryProjectsProjectIdAssetsRouteImport } from './routes/_auth/quarry/projects/$projectId/assets'
import { Route as AuthQuarryEditorProjectIdSlideIdRouteImport } from './routes/_auth/quarry/editor/$projectId/$slideId'
import { Route as AuthQuarryEditorProjectIdCommitIdSlideIdRouteImport } from './routes/_auth/quarry/editor/$projectId/$commitId/$slideId'

const WebPlaceholderRoute = WebPlaceholderRouteImport.update({
  id: '/web-placeholder',
  path: '/web-placeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const WebNonetRoute = WebNonetRouteImport.update({
  id: '/web-nonet',
  path: '/web-nonet',
  getParentRoute: () => rootRouteImport,
} as any)
const WebCorsissueRoute = WebCorsissueRouteImport.update({
  id: '/web-corsissue',
  path: '/web-corsissue',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallIndexRoute = WallIndexRouteImport.update({
  id: '/wall/',
  path: '/wall/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControllerIndexRoute = ControllerIndexRouteImport.update({
  id: '/controller/',
  path: '/controller/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const YjsSplatRoute = YjsSplatRouteImport.update({
  id: '/yjs/$',
  path: '/yjs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadProjectIdRoute = UploadProjectIdRouteImport.update({
  id: '/upload/$projectId',
  path: '/upload/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundNoopRoute = PlaygroundNoopRouteImport.update({
  id: '/playground/noop',
  path: '/playground/noop',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticesRoute = LegalNoticesRouteImport.update({
  id: '/legal/notices',
  path: '/legal/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebScreenshotRoute = ApiWebScreenshotRouteImport.update({
  id: '/api/web-screenshot',
  path: '/api/web-screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportCspRoute = ApiReportCspRouteImport.update({
  id: '/api/report-csp',
  path: '/api/report-csp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestBootstrapRoute = GuestBootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AdminWallsIndexRoute = AdminWallsIndexRouteImport.update({
  id: '/walls/',
  path: '/walls/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthQuarryIndexRoute = AuthQuarryIndexRouteImport.update({
  id: '/quarry/',
  path: '/quarry/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/api/uploads/$',
  path: '/api/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsUriRoute = ApiAssetsUriRouteImport.update({
  id: '/api/assets/$uri',
  path: '/api/assets/$uri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWallsWallIdRouteRoute = AdminWallsWallIdRouteRouteImport.update({
  id: '/walls/$wallId',
  path: '/walls/$wallId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthQuarryProjectsRouteRoute = AuthQuarryProjectsRouteRouteImport.update({
  id: '/quarry/projects',
  path: '/quarry/projects',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthQuarryEditorRouteRoute = AuthQuarryEditorRouteRouteImport.update({
  id: '/quarry/editor',
  path: '/quarry/editor',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminWallsWallIdIndexRoute = AdminWallsWallIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWallsWallIdRouteRoute,
} as any)
const ApiPortalV1RebootRoute = ApiPortalV1RebootRouteImport.update({
  id: '/api/portal/v1/reboot',
  path: '/api/portal/v1/reboot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWallsWallIdDevicesRoute = AdminWallsWallIdDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminWallsWallIdRouteRoute,
} as any)
const AuthQuarryProjectsNewRoute = AuthQuarryProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthQuarryProjectsRouteRoute,
} as any)
const AuthQuarryProjectsProjectIdRouteRoute =
  AuthQuarryProjectsProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthQuarryProjectsRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdIndexRoute =
  AuthQuarryProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryEditorProjectIdIndexRoute =
  AuthQuarryEditorProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => AuthQuarryEditorRouteRoute,
  } as any)
const AuthQuarryViewProjectIdCommitIdRoute =
  AuthQuarryViewProjectIdCommitIdRouteImport.update({
    id: '/quarry/view/$projectId/$commitId',
    path: '/quarry/view/$projectId/$commitId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdPermissionsRoute =
  AuthQuarryProjectsProjectIdPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdHistoryRoute =
  AuthQuarryProjectsProjectIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdCommitsRoute =
  AuthQuarryProjectsProjectIdCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryProjectsProjectIdAssetsRoute =
  AuthQuarryProjectsProjectIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthQuarryProjectsProjectIdRouteRoute,
  } as any)
const AuthQuarryEditorProjectIdSlideIdRoute =
  AuthQuarryEditorProjectIdSlideIdRouteImport.update({
    id: '/$projectId/$slideId',
    path: '/$projectId/$slideId',
    getParentRoute: () => AuthQuarryEditorRouteRoute,
  } as any)
const AuthQuarryEditorProjectIdCommitIdSlideIdRoute =
  AuthQuarryEditorProjectIdCommitIdSlideIdRouteImport.update({
    id: '/$projectId/$commitId/$slideId',
    path: '/$projectId/$commitId/$slideId',
    getParentRoute: () => AuthQuarryEditorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bus': typeof BusRoute
  '/og': typeof OgRoute
  '/web-corsissue': typeof WebCorsissueRoute
  '/web-nonet': typeof WebNonetRoute
  '/web-placeholder': typeof WebPlaceholderRoute
  '/bootstrap': typeof GuestBootstrapRoute
  '/login': typeof GuestLoginRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/report-csp': typeof ApiReportCspRoute
  '/api/web-screenshot': typeof ApiWebScreenshotRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/playground/noop': typeof PlaygroundNoopRoute
  '/upload/$projectId': typeof UploadProjectIdRoute
  '/yjs/$': typeof YjsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/controller/': typeof ControllerIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/wall/': typeof WallIndexRoute
  '/quarry/editor': typeof AuthQuarryEditorRouteRouteWithChildren
  '/quarry/projects': typeof AuthQuarryProjectsRouteRouteWithChildren
  '/admin/walls/$wallId': typeof AdminWallsWallIdRouteRouteWithChildren
  '/api/assets/$uri': typeof ApiAssetsUriRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/quarry/': typeof AuthQuarryIndexRoute
  '/admin/walls/': typeof AdminWallsIndexRoute
  '/quarry/projects/$projectId': typeof AuthQuarryProjectsProjectIdRouteRouteWithChildren
  '/quarry/projects/new': typeof AuthQuarryProjectsNewRoute
  '/admin/walls/$wallId/devices': typeof AdminWallsWallIdDevicesRoute
  '/api/portal/v1/reboot': typeof ApiPortalV1RebootRoute
  '/admin/walls/$wallId/': typeof AdminWallsWallIdIndexRoute
  '/quarry/editor/$projectId/$slideId': typeof AuthQuarryEditorProjectIdSlideIdRoute
  '/quarry/projects/$projectId/assets': typeof AuthQuarryProjectsProjectIdAssetsRoute
  '/quarry/projects/$projectId/commits': typeof AuthQuarryProjectsProjectIdCommitsRoute
  '/quarry/projects/$projectId/history': typeof AuthQuarryProjectsProjectIdHistoryRoute
  '/quarry/projects/$projectId/permissions': typeof AuthQuarryProjectsProjectIdPermissionsRoute
  '/quarry/view/$projectId/$commitId': typeof AuthQuarryViewProjectIdCommitIdRoute
  '/quarry/editor/$projectId/': typeof AuthQuarryEditorProjectIdIndexRoute
  '/quarry/projects/$projectId/': typeof AuthQuarryProjectsProjectIdIndexRoute
  '/quarry/editor/$projectId/$commitId/$slideId': typeof AuthQuarryEditorProjectIdCommitIdSlideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/og': typeof OgRoute
  '/web-corsissue': typeof WebCorsissueRoute
  '/web-nonet': typeof WebNonetRoute
  '/web-placeholder': typeof WebPlaceholderRoute
  '/bootstrap': typeof GuestBootstrapRoute
  '/login': typeof GuestLoginRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/report-csp': typeof ApiReportCspRoute
  '/api/web-screenshot': typeof ApiWebScreenshotRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/playground/noop': typeof PlaygroundNoopRoute
  '/upload/$projectId': typeof UploadProjectIdRoute
  '/yjs/$': typeof YjsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/controller': typeof ControllerIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/wall': typeof WallIndexRoute
  '/quarry/editor': typeof AuthQuarryEditorRouteRouteWithChildren
  '/quarry/projects': typeof AuthQuarryProjectsRouteRouteWithChildren
  '/api/assets/$uri': typeof ApiAssetsUriRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/quarry': typeof AuthQuarryIndexRoute
  '/admin/walls': typeof AdminWallsIndexRoute
  '/quarry/projects/new': typeof AuthQuarryProjectsNewRoute
  '/admin/walls/$wallId/devices': typeof AdminWallsWallIdDevicesRoute
  '/api/portal/v1/reboot': typeof ApiPortalV1RebootRoute
  '/admin/walls/$wallId': typeof AdminWallsWallIdIndexRoute
  '/quarry/editor/$projectId/$slideId': typeof AuthQuarryEditorProjectIdSlideIdRoute
  '/quarry/projects/$projectId/assets': typeof AuthQuarryProjectsProjectIdAssetsRoute
  '/quarry/projects/$projectId/commits': typeof AuthQuarryProjectsProjectIdCommitsRoute
  '/quarry/projects/$projectId/history': typeof AuthQuarryProjectsProjectIdHistoryRoute
  '/quarry/projects/$projectId/permissions': typeof AuthQuarryProjectsProjectIdPermissionsRoute
  '/quarry/view/$projectId/$commitId': typeof AuthQuarryViewProjectIdCommitIdRoute
  '/quarry/editor/$projectId': typeof AuthQuarryEditorProjectIdIndexRoute
  '/quarry/projects/$projectId': typeof AuthQuarryProjectsProjectIdIndexRoute
  '/quarry/editor/$projectId/$commitId/$slideId': typeof AuthQuarryEditorProjectIdCommitIdSlideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/bus': typeof BusRoute
  '/og': typeof OgRoute
  '/web-corsissue': typeof WebCorsissueRoute
  '/web-nonet': typeof WebNonetRoute
  '/web-placeholder': typeof WebPlaceholderRoute
  '/_guest/bootstrap': typeof GuestBootstrapRoute
  '/_guest/login': typeof GuestLoginRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/report-csp': typeof ApiReportCspRoute
  '/api/web-screenshot': typeof ApiWebScreenshotRoute
  '/legal/notices': typeof LegalNoticesRoute
  '/playground/noop': typeof PlaygroundNoopRoute
  '/upload/$projectId': typeof UploadProjectIdRoute
  '/yjs/$': typeof YjsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/controller/': typeof ControllerIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/wall/': typeof WallIndexRoute
  '/_auth/quarry/editor': typeof AuthQuarryEditorRouteRouteWithChildren
  '/_auth/quarry/projects': typeof AuthQuarryProjectsRouteRouteWithChildren
  '/admin/walls/$wallId': typeof AdminWallsWallIdRouteRouteWithChildren
  '/api/assets/$uri': typeof ApiAssetsUriRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/_auth/quarry/': typeof AuthQuarryIndexRoute
  '/admin/walls/': typeof AdminWallsIndexRoute
  '/_auth/quarry/projects/$projectId': typeof AuthQuarryProjectsProjectIdRouteRouteWithChildren
  '/_auth/quarry/projects/new': typeof AuthQuarryProjectsNewRoute
  '/admin/walls/$wallId/devices': typeof AdminWallsWallIdDevicesRoute
  '/api/portal/v1/reboot': typeof ApiPortalV1RebootRoute
  '/admin/walls/$wallId/': typeof AdminWallsWallIdIndexRoute
  '/_auth/quarry/editor/$projectId/$slideId': typeof AuthQuarryEditorProjectIdSlideIdRoute
  '/_auth/quarry/projects/$projectId/assets': typeof AuthQuarryProjectsProjectIdAssetsRoute
  '/_auth/quarry/projects/$projectId/commits': typeof AuthQuarryProjectsProjectIdCommitsRoute
  '/_auth/quarry/projects/$projectId/history': typeof AuthQuarryProjectsProjectIdHistoryRoute
  '/_auth/quarry/projects/$projectId/permissions': typeof AuthQuarryProjectsProjectIdPermissionsRoute
  '/_auth/quarry/view/$projectId/$commitId': typeof AuthQuarryViewProjectIdCommitIdRoute
  '/_auth/quarry/editor/$projectId/': typeof AuthQuarryEditorProjectIdIndexRoute
  '/_auth/quarry/projects/$projectId/': typeof AuthQuarryProjectsProjectIdIndexRoute
  '/_auth/quarry/editor/$projectId/$commitId/$slideId': typeof AuthQuarryEditorProjectIdCommitIdSlideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bus'
    | '/og'
    | '/web-corsissue'
    | '/web-nonet'
    | '/web-placeholder'
    | '/bootstrap'
    | '/login'
    | '/admin/assets'
    | '/admin/config'
    | '/admin/devices'
    | '/admin/projects'
    | '/admin/stats'
    | '/admin/users'
    | '/api/report-csp'
    | '/api/web-screenshot'
    | '/legal/notices'
    | '/playground/noop'
    | '/upload/$projectId'
    | '/yjs/$'
    | '/admin/'
    | '/controller/'
    | '/gallery/'
    | '/playground/'
    | '/wall/'
    | '/quarry/editor'
    | '/quarry/projects'
    | '/admin/walls/$wallId'
    | '/api/assets/$uri'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/quarry/'
    | '/admin/walls/'
    | '/quarry/projects/$projectId'
    | '/quarry/projects/new'
    | '/admin/walls/$wallId/devices'
    | '/api/portal/v1/reboot'
    | '/admin/walls/$wallId/'
    | '/quarry/editor/$projectId/$slideId'
    | '/quarry/projects/$projectId/assets'
    | '/quarry/projects/$projectId/commits'
    | '/quarry/projects/$projectId/history'
    | '/quarry/projects/$projectId/permissions'
    | '/quarry/view/$projectId/$commitId'
    | '/quarry/editor/$projectId/'
    | '/quarry/projects/$projectId/'
    | '/quarry/editor/$projectId/$commitId/$slideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus'
    | '/og'
    | '/web-corsissue'
    | '/web-nonet'
    | '/web-placeholder'
    | '/bootstrap'
    | '/login'
    | '/admin/assets'
    | '/admin/config'
    | '/admin/devices'
    | '/admin/projects'
    | '/admin/stats'
    | '/admin/users'
    | '/api/report-csp'
    | '/api/web-screenshot'
    | '/legal/notices'
    | '/playground/noop'
    | '/upload/$projectId'
    | '/yjs/$'
    | '/admin'
    | '/controller'
    | '/gallery'
    | '/playground'
    | '/wall'
    | '/quarry/editor'
    | '/quarry/projects'
    | '/api/assets/$uri'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/quarry'
    | '/admin/walls'
    | '/quarry/projects/new'
    | '/admin/walls/$wallId/devices'
    | '/api/portal/v1/reboot'
    | '/admin/walls/$wallId'
    | '/quarry/editor/$projectId/$slideId'
    | '/quarry/projects/$projectId/assets'
    | '/quarry/projects/$projectId/commits'
    | '/quarry/projects/$projectId/history'
    | '/quarry/projects/$projectId/permissions'
    | '/quarry/view/$projectId/$commitId'
    | '/quarry/editor/$projectId'
    | '/quarry/projects/$projectId'
    | '/quarry/editor/$projectId/$commitId/$slideId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/admin'
    | '/bus'
    | '/og'
    | '/web-corsissue'
    | '/web-nonet'
    | '/web-placeholder'
    | '/_guest/bootstrap'
    | '/_guest/login'
    | '/admin/assets'
    | '/admin/config'
    | '/admin/devices'
    | '/admin/projects'
    | '/admin/stats'
    | '/admin/users'
    | '/api/report-csp'
    | '/api/web-screenshot'
    | '/legal/notices'
    | '/playground/noop'
    | '/upload/$projectId'
    | '/yjs/$'
    | '/admin/'
    | '/controller/'
    | '/gallery/'
    | '/playground/'
    | '/wall/'
    | '/_auth/quarry/editor'
    | '/_auth/quarry/projects'
    | '/admin/walls/$wallId'
    | '/api/assets/$uri'
    | '/api/auth/$'
    | '/api/uploads/$'
    | '/_auth/quarry/'
    | '/admin/walls/'
    | '/_auth/quarry/projects/$projectId'
    | '/_auth/quarry/projects/new'
    | '/admin/walls/$wallId/devices'
    | '/api/portal/v1/reboot'
    | '/admin/walls/$wallId/'
    | '/_auth/quarry/editor/$projectId/$slideId'
    | '/_auth/quarry/projects/$projectId/assets'
    | '/_auth/quarry/projects/$projectId/commits'
    | '/_auth/quarry/projects/$projectId/history'
    | '/_auth/quarry/projects/$projectId/permissions'
    | '/_auth/quarry/view/$projectId/$commitId'
    | '/_auth/quarry/editor/$projectId/'
    | '/_auth/quarry/projects/$projectId/'
    | '/_auth/quarry/editor/$projectId/$commitId/$slideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BusRoute: typeof BusRoute
  OgRoute: typeof OgRoute
  WebCorsissueRoute: typeof WebCorsissueRoute
  WebNonetRoute: typeof WebNonetRoute
  WebPlaceholderRoute: typeof WebPlaceholderRoute
  ApiReportCspRoute: typeof ApiReportCspRoute
  ApiWebScreenshotRoute: typeof ApiWebScreenshotRoute
  LegalNoticesRoute: typeof LegalNoticesRoute
  PlaygroundNoopRoute: typeof PlaygroundNoopRoute
  UploadProjectIdRoute: typeof UploadProjectIdRoute
  YjsSplatRoute: typeof YjsSplatRoute
  ControllerIndexRoute: typeof ControllerIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  WallIndexRoute: typeof WallIndexRoute
  ApiAssetsUriRoute: typeof ApiAssetsUriRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
  ApiPortalV1RebootRoute: typeof ApiPortalV1RebootRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-placeholder': {
      id: '/web-placeholder'
      path: '/web-placeholder'
      fullPath: '/web-placeholder'
      preLoaderRoute: typeof WebPlaceholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-nonet': {
      id: '/web-nonet'
      path: '/web-nonet'
      fullPath: '/web-nonet'
      preLoaderRoute: typeof WebNonetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-corsissue': {
      id: '/web-corsissue'
      path: '/web-corsissue'
      fullPath: '/web-corsissue'
      preLoaderRoute: typeof WebCorsissueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall/': {
      id: '/wall/'
      path: '/wall'
      fullPath: '/wall/'
      preLoaderRoute: typeof WallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controller/': {
      id: '/controller/'
      path: '/controller'
      fullPath: '/controller/'
      preLoaderRoute: typeof ControllerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/yjs/$': {
      id: '/yjs/$'
      path: '/yjs/$'
      fullPath: '/yjs/$'
      preLoaderRoute: typeof YjsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$projectId': {
      id: '/upload/$projectId'
      path: '/upload/$projectId'
      fullPath: '/upload/$projectId'
      preLoaderRoute: typeof UploadProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/noop': {
      id: '/playground/noop'
      path: '/playground/noop'
      fullPath: '/playground/noop'
      preLoaderRoute: typeof PlaygroundNoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/notices': {
      id: '/legal/notices'
      path: '/legal/notices'
      fullPath: '/legal/notices'
      preLoaderRoute: typeof LegalNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-screenshot': {
      id: '/api/web-screenshot'
      path: '/api/web-screenshot'
      fullPath: '/api/web-screenshot'
      preLoaderRoute: typeof ApiWebScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report-csp': {
      id: '/api/report-csp'
      path: '/api/report-csp'
      fullPath: '/api/report-csp'
      preLoaderRoute: typeof ApiReportCspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/bootstrap': {
      id: '/_guest/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof GuestBootstrapRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/admin/walls/': {
      id: '/admin/walls/'
      path: '/walls'
      fullPath: '/admin/walls/'
      preLoaderRoute: typeof AdminWallsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/quarry/': {
      id: '/_auth/quarry/'
      path: '/quarry'
      fullPath: '/quarry/'
      preLoaderRoute: typeof AuthQuarryIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/api/uploads/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$uri': {
      id: '/api/assets/$uri'
      path: '/api/assets/$uri'
      fullPath: '/api/assets/$uri'
      preLoaderRoute: typeof ApiAssetsUriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/walls/$wallId': {
      id: '/admin/walls/$wallId'
      path: '/walls/$wallId'
      fullPath: '/admin/walls/$wallId'
      preLoaderRoute: typeof AdminWallsWallIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/quarry/projects': {
      id: '/_auth/quarry/projects'
      path: '/quarry/projects'
      fullPath: '/quarry/projects'
      preLoaderRoute: typeof AuthQuarryProjectsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/quarry/editor': {
      id: '/_auth/quarry/editor'
      path: '/quarry/editor'
      fullPath: '/quarry/editor'
      preLoaderRoute: typeof AuthQuarryEditorRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/walls/$wallId/': {
      id: '/admin/walls/$wallId/'
      path: '/'
      fullPath: '/admin/walls/$wallId/'
      preLoaderRoute: typeof AdminWallsWallIdIndexRouteImport
      parentRoute: typeof AdminWallsWallIdRouteRoute
    }
    '/api/portal/v1/reboot': {
      id: '/api/portal/v1/reboot'
      path: '/api/portal/v1/reboot'
      fullPath: '/api/portal/v1/reboot'
      preLoaderRoute: typeof ApiPortalV1RebootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/walls/$wallId/devices': {
      id: '/admin/walls/$wallId/devices'
      path: '/devices'
      fullPath: '/admin/walls/$wallId/devices'
      preLoaderRoute: typeof AdminWallsWallIdDevicesRouteImport
      parentRoute: typeof AdminWallsWallIdRouteRoute
    }
    '/_auth/quarry/projects/new': {
      id: '/_auth/quarry/projects/new'
      path: '/new'
      fullPath: '/quarry/projects/new'
      preLoaderRoute: typeof AuthQuarryProjectsNewRouteImport
      parentRoute: typeof AuthQuarryProjectsRouteRoute
    }
    '/_auth/quarry/projects/$projectId': {
      id: '/_auth/quarry/projects/$projectId'
      path: '/$projectId'
      fullPath: '/quarry/projects/$projectId'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthQuarryProjectsRouteRoute
    }
    '/_auth/quarry/projects/$projectId/': {
      id: '/_auth/quarry/projects/$projectId/'
      path: '/'
      fullPath: '/quarry/projects/$projectId/'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/editor/$projectId/': {
      id: '/_auth/quarry/editor/$projectId/'
      path: '/$projectId'
      fullPath: '/quarry/editor/$projectId/'
      preLoaderRoute: typeof AuthQuarryEditorProjectIdIndexRouteImport
      parentRoute: typeof AuthQuarryEditorRouteRoute
    }
    '/_auth/quarry/view/$projectId/$commitId': {
      id: '/_auth/quarry/view/$projectId/$commitId'
      path: '/quarry/view/$projectId/$commitId'
      fullPath: '/quarry/view/$projectId/$commitId'
      preLoaderRoute: typeof AuthQuarryViewProjectIdCommitIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/quarry/projects/$projectId/permissions': {
      id: '/_auth/quarry/projects/$projectId/permissions'
      path: '/permissions'
      fullPath: '/quarry/projects/$projectId/permissions'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdPermissionsRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/projects/$projectId/history': {
      id: '/_auth/quarry/projects/$projectId/history'
      path: '/history'
      fullPath: '/quarry/projects/$projectId/history'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdHistoryRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/projects/$projectId/commits': {
      id: '/_auth/quarry/projects/$projectId/commits'
      path: '/commits'
      fullPath: '/quarry/projects/$projectId/commits'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdCommitsRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/projects/$projectId/assets': {
      id: '/_auth/quarry/projects/$projectId/assets'
      path: '/assets'
      fullPath: '/quarry/projects/$projectId/assets'
      preLoaderRoute: typeof AuthQuarryProjectsProjectIdAssetsRouteImport
      parentRoute: typeof AuthQuarryProjectsProjectIdRouteRoute
    }
    '/_auth/quarry/editor/$projectId/$slideId': {
      id: '/_auth/quarry/editor/$projectId/$slideId'
      path: '/$projectId/$slideId'
      fullPath: '/quarry/editor/$projectId/$slideId'
      preLoaderRoute: typeof AuthQuarryEditorProjectIdSlideIdRouteImport
      parentRoute: typeof AuthQuarryEditorRouteRoute
    }
    '/_auth/quarry/editor/$projectId/$commitId/$slideId': {
      id: '/_auth/quarry/editor/$projectId/$commitId/$slideId'
      path: '/$projectId/$commitId/$slideId'
      fullPath: '/quarry/editor/$projectId/$commitId/$slideId'
      preLoaderRoute: typeof AuthQuarryEditorProjectIdCommitIdSlideIdRouteImport
      parentRoute: typeof AuthQuarryEditorRouteRoute
    }
  }
}

interface AuthQuarryEditorRouteRouteChildren {
  AuthQuarryEditorProjectIdSlideIdRoute: typeof AuthQuarryEditorProjectIdSlideIdRoute
  AuthQuarryEditorProjectIdIndexRoute: typeof AuthQuarryEditorProjectIdIndexRoute
  AuthQuarryEditorProjectIdCommitIdSlideIdRoute: typeof AuthQuarryEditorProjectIdCommitIdSlideIdRoute
}

const AuthQuarryEditorRouteRouteChildren: AuthQuarryEditorRouteRouteChildren = {
  AuthQuarryEditorProjectIdSlideIdRoute: AuthQuarryEditorProjectIdSlideIdRoute,
  AuthQuarryEditorProjectIdIndexRoute: AuthQuarryEditorProjectIdIndexRoute,
  AuthQuarryEditorProjectIdCommitIdSlideIdRoute:
    AuthQuarryEditorProjectIdCommitIdSlideIdRoute,
}

const AuthQuarryEditorRouteRouteWithChildren =
  AuthQuarryEditorRouteRoute._addFileChildren(
    AuthQuarryEditorRouteRouteChildren,
  )

interface AuthQuarryProjectsProjectIdRouteRouteChildren {
  AuthQuarryProjectsProjectIdAssetsRoute: typeof AuthQuarryProjectsProjectIdAssetsRoute
  AuthQuarryProjectsProjectIdCommitsRoute: typeof AuthQuarryProjectsProjectIdCommitsRoute
  AuthQuarryProjectsProjectIdHistoryRoute: typeof AuthQuarryProjectsProjectIdHistoryRoute
  AuthQuarryProjectsProjectIdPermissionsRoute: typeof AuthQuarryProjectsProjectIdPermissionsRoute
  AuthQuarryProjectsProjectIdIndexRoute: typeof AuthQuarryProjectsProjectIdIndexRoute
}

const AuthQuarryProjectsProjectIdRouteRouteChildren: AuthQuarryProjectsProjectIdRouteRouteChildren =
  {
    AuthQuarryProjectsProjectIdAssetsRoute:
      AuthQuarryProjectsProjectIdAssetsRoute,
    AuthQuarryProjectsProjectIdCommitsRoute:
      AuthQuarryProjectsProjectIdCommitsRoute,
    AuthQuarryProjectsProjectIdHistoryRoute:
      AuthQuarryProjectsProjectIdHistoryRoute,
    AuthQuarryProjectsProjectIdPermissionsRoute:
      AuthQuarryProjectsProjectIdPermissionsRoute,
    AuthQuarryProjectsProjectIdIndexRoute:
      AuthQuarryProjectsProjectIdIndexRoute,
  }

const AuthQuarryProjectsProjectIdRouteRouteWithChildren =
  AuthQuarryProjectsProjectIdRouteRoute._addFileChildren(
    AuthQuarryProjectsProjectIdRouteRouteChildren,
  )

interface AuthQuarryProjectsRouteRouteChildren {
  AuthQuarryProjectsProjectIdRouteRoute: typeof AuthQuarryProjectsProjectIdRouteRouteWithChildren
  AuthQuarryProjectsNewRoute: typeof AuthQuarryProjectsNewRoute
}

const AuthQuarryProjectsRouteRouteChildren: AuthQuarryProjectsRouteRouteChildren =
  {
    AuthQuarryProjectsProjectIdRouteRoute:
      AuthQuarryProjectsProjectIdRouteRouteWithChildren,
    AuthQuarryProjectsNewRoute: AuthQuarryProjectsNewRoute,
  }

const AuthQuarryProjectsRouteRouteWithChildren =
  AuthQuarryProjectsRouteRoute._addFileChildren(
    AuthQuarryProjectsRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthQuarryEditorRouteRoute: typeof AuthQuarryEditorRouteRouteWithChildren
  AuthQuarryProjectsRouteRoute: typeof AuthQuarryProjectsRouteRouteWithChildren
  AuthQuarryIndexRoute: typeof AuthQuarryIndexRoute
  AuthQuarryViewProjectIdCommitIdRoute: typeof AuthQuarryViewProjectIdCommitIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthQuarryEditorRouteRoute: AuthQuarryEditorRouteRouteWithChildren,
  AuthQuarryProjectsRouteRoute: AuthQuarryProjectsRouteRouteWithChildren,
  AuthQuarryIndexRoute: AuthQuarryIndexRoute,
  AuthQuarryViewProjectIdCommitIdRoute: AuthQuarryViewProjectIdCommitIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestBootstrapRoute: typeof GuestBootstrapRoute
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestBootstrapRoute: GuestBootstrapRoute,
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface AdminWallsWallIdRouteRouteChildren {
  AdminWallsWallIdDevicesRoute: typeof AdminWallsWallIdDevicesRoute
  AdminWallsWallIdIndexRoute: typeof AdminWallsWallIdIndexRoute
}

const AdminWallsWallIdRouteRouteChildren: AdminWallsWallIdRouteRouteChildren = {
  AdminWallsWallIdDevicesRoute: AdminWallsWallIdDevicesRoute,
  AdminWallsWallIdIndexRoute: AdminWallsWallIdIndexRoute,
}

const AdminWallsWallIdRouteRouteWithChildren =
  AdminWallsWallIdRouteRoute._addFileChildren(
    AdminWallsWallIdRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWallsWallIdRouteRoute: typeof AdminWallsWallIdRouteRouteWithChildren
  AdminWallsIndexRoute: typeof AdminWallsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAssetsRoute: AdminAssetsRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWallsWallIdRouteRoute: AdminWallsWallIdRouteRouteWithChildren,
  AdminWallsIndexRoute: AdminWallsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BusRoute: BusRoute,
  OgRoute: OgRoute,
  WebCorsissueRoute: WebCorsissueRoute,
  WebNonetRoute: WebNonetRoute,
  WebPlaceholderRoute: WebPlaceholderRoute,
  ApiReportCspRoute: ApiReportCspRoute,
  ApiWebScreenshotRoute: ApiWebScreenshotRoute,
  LegalNoticesRoute: LegalNoticesRoute,
  PlaygroundNoopRoute: PlaygroundNoopRoute,
  UploadProjectIdRoute: UploadProjectIdRoute,
  YjsSplatRoute: YjsSplatRoute,
  ControllerIndexRoute: ControllerIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  WallIndexRoute: WallIndexRoute,
  ApiAssetsUriRoute: ApiAssetsUriRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
  ApiPortalV1RebootRoute: ApiPortalV1RebootRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
