/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthQuarryRouteRouteImport } from './routes/_auth/quarry/route'
import { Route as AuthQuarryIndexRouteImport } from './routes/_auth/quarry/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthQuarryRouteRoute = AuthQuarryRouteRouteImport.update({
  id: '/quarry',
  path: '/quarry',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthQuarryIndexRoute = AuthQuarryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthQuarryRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quarry': typeof AuthQuarryRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quarry/': typeof AuthQuarryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quarry': typeof AuthQuarryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/quarry': typeof AuthQuarryRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/quarry/': typeof AuthQuarryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quarry' | '/login' | '/api/auth/$' | '/quarry/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/auth/$' | '/quarry'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/quarry'
    | '/_guest/login'
    | '/api/auth/$'
    | '/_auth/quarry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/quarry': {
      id: '/_auth/quarry'
      path: '/quarry'
      fullPath: '/quarry'
      preLoaderRoute: typeof AuthQuarryRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/quarry/': {
      id: '/_auth/quarry/'
      path: '/'
      fullPath: '/quarry/'
      preLoaderRoute: typeof AuthQuarryIndexRouteImport
      parentRoute: typeof AuthQuarryRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthQuarryRouteRouteChildren {
  AuthQuarryIndexRoute: typeof AuthQuarryIndexRoute
}

const AuthQuarryRouteRouteChildren: AuthQuarryRouteRouteChildren = {
  AuthQuarryIndexRoute: AuthQuarryIndexRoute,
}

const AuthQuarryRouteRouteWithChildren = AuthQuarryRouteRoute._addFileChildren(
  AuthQuarryRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthQuarryRouteRoute: typeof AuthQuarryRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthQuarryRouteRoute: AuthQuarryRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
